### ISSUE TITLE
Custom Document Well: Incorrect or unexpected tab coloring

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/VS-PPT#22]
**Environment:**
Windows 10 64bit
Visual Studio 2015 Professional
Productivity Power Tools 14.0.23120.0

**To Reproduce**
General -> Tab Appearance: Disable color tabs by project
General -> Tab Appearance: Enable color tabs by regular expression
Advanced -> Colors and Gradients -> Selected tab: VS Colors
1. Create at least one tab colored by regex
2. Select the colored tab
3. Select anything that will make the colored tab lose focus (such as a different tab group)

**Issue**
After losing focus the colored tab should display some variant of the regex color (such as the one used when 'Default' is picked instead of 'VS Colors'), or there should be an option to do so.  Instead, the unfocused, selected tab uses Visual Studio's coloring. This is a slight variant of the default VS tab color.

**Comment by MartinL0815** [comment]
I would like to extend this issue:

1. I work with enabled high-contrast-mode (yellow text, white frames, black backgrounds, etc.)
2. The custom document well has project related coloring enabled
3. The foreground and the background colors do not have the necessary contrast are too near to be read well, since the tab coloring is not disabled in high-contrast-mode

Possible solutions:

1. disable coloring at all with enabled high-contrast-mode
2. do not color the complete tab, but …
  - only a small area, like the buttons area (pin, close) or
  - a small horizontal bar at the top or
  - a small vertical bar at the left

Cheers,

Martin

**Comment by kmgallahan** [comment]
No longer relevant since the Custom Document Well is unsupported in VS 2019 and the functionality is [being rebuilt in VS itself](https://developercommunity.visualstudio.com/content/idea/465490/update-support-for-custom-document-well-to-visual.html).
