### ISSUE TITLE
Visual Studio crashes a lot when debugging and just copying paste, says preparing copying, and have already disabled html copy

### ISSUE THREAD

**Issue by brunobola** [Microsoft/VS-PPT#31]
Visual Studio crashes a lot when debugging and just copying paste, says preparing copying, and have already disabled html copy...

please help

**Comment by KirillOsenkov** [comment]
In order to understand what exactly the problem is we need to look at a call stack of the crash. You can try using the instructions here to attach a debugger to Visual Studio before it crashes and get us a call stack:
https://blogs.msdn.microsoft.com/kirillosenkov/2008/12/07/how-to-debug-crashes-and-hangs

**Comment by dontnet** [comment]
In my experience this tool just crashes vs all the time. Switching to an already open xaml-file or opening a new one is an almost sure way to crash vs with this tool.
I use VS2015 Professional Update 2 on a Hyper-V 64 win10 guest/host.
used to crash all the time (copy, paste, switch a file etc. (xaml seems to intensify crash likelyhood)
de-installed it somewhere end of 2015 = all good
re-installed a few days ago (update popped up in vs promising crash fix), problems back, so maybe a few crash scenarios were eliminated, but it just crashes all the time. Had to remove it again, real pity. used to love it, had been using it since years, Never really worked (as in not regularly crashing vs) with vs2015.
After last crash intellisense/xaml in vs gone

**Comment by brunobola** [comment]
After some debug, was a memory leak of a plug-in, respectively coderush from devexpress.

**Comment by dontnet** [comment]
Didn't have coderush or any devexpress stuff unless ms delivers it per
default.
