### ISSUE TITLE
Tab Reorder/Sort Fails

### ISSUE THREAD

**Issue by real-napster** [Microsoft/VS-PPT#73]
![tabreorderfail](https://cloud.githubusercontent.com/assets/4245739/21809073/70cd7d0c-d746-11e6-8c17-4b052e9f68bc.gif)

As you can see: When I try to reorder the third Tab to the second Place and then click on the "new third" Tab, the Reorder fails and it jumps back to before

**Comment by roeba** [comment]
Can anyone comment on this? I have disabled sorting in the custom document well, the only thing enabled is the coloring for projects. I have the same problem and would like to bump it.

**Comment by justcla** [comment]
Can you please describe the problem?

**Comment by roeba** [comment]
Sure. Imagine you have three tabs, A B C in that order. You select tab B and move it to the right side of C, so that the order is now A C B.
If you now select any other tab than B (so A or C), the original order A B C will be restored. The one you just made is discarded. If I deactivate the custom document well it works.

Correct behaviour with custom document well disabled:
![ok](https://cloud.githubusercontent.com/assets/27268894/25275219/6f311b0a-2694-11e7-88ab-109b9a581f76.gif)

Wrong behaviour:
![nok](https://cloud.githubusercontent.com/assets/27268894/25275239/837addf8-2694-11e7-8ce0-9a141f4a2797.gif)

**Comment by justcla** [comment]
@roeba What you're seeing is a feature (on by default) to sort tabs alphabetically.
To disable this sorting behavior, go to Tools->Options; Productivity Power Tools->Custom Document Well.
In the "Sorting" group you'll see an option to sort "Alphabetically". Uncheck that box to stop the tabs automatically ordering themselves by name.

![image](https://cloud.githubusercontent.com/assets/17131343/25286067/492b597a-2671-11e7-918c-fe4f6445ca6d.png)

**Comment by roeba** [comment]
@justcla You were right. I thought that I deactivated all those options other than coloring before, but they were enabled and thus sorting was alphabetically. Thank you!
