### ISSUE TITLE
"HTML Copy" settings on "Productivity Power Tools" node in Settings

### ISSUE THREAD

**Issue by JVimes** [Microsoft/VS-PPT#90]
I'm on 2017 RC4. This seems like a bug:
![2017-02-09_10h05_48](https://cloud.githubusercontent.com/assets/6148201/22794263/c939cc86-eeaf-11e6-8385-f832312a2819.png)

**Comment by justcla** [comment]
Hi JVimes. Thanks for opening the issue.
What you're seeing is default behavior in the Tools Options dialog.
Expandable nodes do not contain content. Instead they simply reflect the content of the first non-node child that appears underneath. Most people use a "General" page to store some settings that apply to the node at a high level. PPT used to have a general page that would let you control which extensions were on and off. That has been removed now because the feature can now be installed as independent extensions. As such, the PPT node now shows different pages depending on your current setup.
In this example, HTML copy was not installed, but Ctrl+Click GoToDefinition was, and it includes options on a page called "Other Extensions". As this is the first non-node child, its contents are shown when you click the PPT node.
![image](https://cloud.githubusercontent.com/assets/17131343/22797913/ed85f9ac-eeb4-11e6-96eb-7a9c6d20f425.png)

**Comment by justcla** [comment]
Perhaps, for consistency, we could create a new "General" options page for PPT and include it as an embedded extension in all PPT extensions.
This is what we currently do with Ctrl+Click GoTo Defn, Shrink Empty Lines, Timestamp Margin and Match Margin so that they have the "Other Extensions" page included. We could consider making that the "General" page. When it's empty, we could add some text or links. (Ideas)

But any of this would introduce added complexity. The benefit would only be to remove an additional access point to certain settings. So I'm not sure if we should.

**Comment by JVimes** [comment]
Ah, thanks. It's low impact. The only risk is getting the occasional report like this one ;) A General page could just be informational ("Below are settings for extensions in the Productivity Power Tools collection."). But I'm fine leaving it as-is.
